version: 2
axioms:
  licensee: license
rules:

  gh-description-set:
    level: error
    rule:
      type: file-contents
      options:
        globsAll:
          - "github.com"
        content: description_set
        human-readable-content: "a repository description in Github settings"

  gh-topics-set:
    level: error
    rule:
      type: file-contents
      options:
        globsAll:
          - "github.com"
        content: topics_set
        human-readable-content: "repository topics in Github settings"    
  
  license-detectable-by-licensee:
    level: error
    where: ["license=MIT","license=Apache-2.0"]
    rule:
      type: license-detectable-by-licensee 

  readme-file-exists:
    level: error
    rule:
      type: file-existence
      options:
        globsAny:
          - "README*"
        nocase: true

  contributing-file-exists:
    level: error
    rule:
      type: file-existence
      options:
        globsAny:
          - "docs/"
          - ".github/"
          - "CONTRIB*"
        nocase: true



   

