version: 2
axioms:
  licensee: license
rules:
  license-file-exists:
    level: error
    rule:
      type: file-existence
      options:
        globsAny:
          - "LICENSE*"
        nocase: true

  readme-file-exists:
    level: error
    rule:
      type: file-existence
      options:
        globsAny:
          - "README*"
        nocase: true

  contributing-file-exists:
    level: error
    rule:
      type: file-existence
      options:
        globsAny:
          - "docs/"
          - ".github/"
          - "CONTRIB*"
        nocase: true

  readme-references-license:
    level: error
    rule:
      type: file-contents
      options:
        globsAll:
          - "README*"
        content: license
        flags: i

  repository-description-set:
    level: error
    rule:
      type: file-contents
      options:
        globsAll:
          - "GITHUB_SETTINGS"
        content: description_set
        human-readable-content: "a repository description in Github"

  repository-topics-set:
    level: error
    rule:
      type: file-contents
      options:
        globsAll:
          - "GITHUB_SETTINGS"
        content: topics_set
        human-readable-content: "repository topics in Github"       

  license-detectable-by-licensee:
    level: error
    where: ["license=*"]
    rule:
      type: license-detectable-by-licensee 