test-archival:
	../archive_repos.sh --org ospo-sandbox --config ./test/archival.yaml 

test-policies:
	../lint_repos.sh --org ospo-sandbox --config ./test/policies.yaml 

test-repos:
	../create_repos.sh --org ospo-sandbox --config ./test/repos.yaml 