---
name: Run create repos
on:
  workflow_dispatch: null
  pull_request:
    paths:
      - 'config/repos.yaml'
  push:
    paths:
      - 'config/repos.yaml'
    branches:
      - main

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Plan github organization changes
        id: plan
        env:
          GH_TOKEN: ${{secrets.TOKEN}}
        run: |
          scripts/create_repos.sh >> result.txt
          cat result.txt
          
      - name: Add output to PR comment
        uses: actions/github-script@v5
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
              const fs = require('fs');
              const outputFilePath = 'result.txt';
              const fileContent = fs.readFileSync(outputFilePath, 'utf-8');
              const prefix = 'Prefix text```\n';
              const suffix = '\n```Suffix text';
              const output = `${prefix}${fileContent}${suffix}`;
          
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `Repository creation output:\n${output}`,
              });

  apply:
    needs: dry-run
    environment: github.com
    if: github.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create repositories and teams
        env:
          GH_TOKEN: ${{secrets.TOKEN}}
        run: scripts/create_repos.sh --apply
