---
name: Run create repos
on:
  workflow_dispatch: null
jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
          owner: allianz

      - name: Create repositories and teams
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: scripts/create_repos.sh --debug


