---
name: Run create repos
on:
  workflow_dispatch: null
  push:
    paths:
      - 'config/repos.yaml'
  pull_request:
    paths:
      - 'config/repos.yaml'

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create repositories and teams
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: scripts/create_repos.sh --debug

  apply:
    needs: dry-run
    environment: github.com
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create repositories and teams
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: scripts/create_repos.sh --apply
