---
name: Run repolint
on:
  workflow_dispatch: null
  # schedule:
  #  - cron: '0 0 * * 2,4'
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node for repolinter
        uses: actions/setup-node@v3

      - name: Setup ruby for license checker
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install dependencies
        run: |
          npm install -g repolinter
          gem install licensee

      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.ALLIANZ_APP_ID }}
          private-key: ${{ secrets.ALLIANZ_PRIVATE_KEY }}

      - name: Lint Allianz Repos
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: scripts/lint_repos.sh --org allianz 

      - uses: actions/upload-artifact@v4
        with:
          name: reports
          path: results
