---
name: Run repolint
on:
  workflow_dispatch: null
  # schedule:
  # - cron: '*/5 * * * *'
  #  - cron: '0 0 * * *'
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node for repolinter
        uses: actions/setup-node@v3

      - name: Setup ruby for license checker
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install dependencies
        run: |
          npm install -g repolinter
          gem install licensee

      - name: Checkout
        uses: actions/checkout@v4

      - uses: tibdex/github-app-token@v2
        id: get_installation_token
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Lint Allianz Incubator Repos
        env:
          GH_TOKEN: ${{ steps.get_installation_token.outputs.token }}
        run: scripts/lint_repos.sh allianz-incubator

      - name: Lint Allianz Repos
        env:
          GH_TOKEN: ${{ steps.get_installation_token.outputs.token }}
        run: scripts/lint_repos.sh allianz --dry-run
